"use client";

import { useEffect, useState } from "react";

const wa = "https://wa.me/554396740022?text=Ol%C3%A1%2C%20Thais%21%20Encontrei%20seu%20site%20e%20gostaria%20de%20saber%20mais%20sobre%20os%20atendimentos%20psicol%C3%B3gicos.";
const instagram = "https://www.instagram.com/psicthaisborges?utm_source=ig_web_button_share_sheet&igsh=ZDNlZDc0MzIxNw==";

const icons: Record<string, React.ReactNode> = {
  menu: <><path d="M4 7h16M4 12h16M4 17h16"/></>, x: <><path d="m6 6 12 12M18 6 6 18"/></>,
  arrow: <><path d="M5 12h14m-5-5 5 5-5 5"/></>, heart: <><path d="M20.8 4.6a5.5 5.5 0 0 0-7.8 0L12 5.7l-1.1-1.1a5.5 5.5 0 0 0-7.8 7.8l1.1 1.1L12 21l7.8-7.5a5.5 5.5 0 0 0 1-8.9Z"/></>,
  brain: <><path d="M9.5 4.5A3 3 0 0 0 4 6v1.5A3.5 3.5 0 0 0 3 14a3 3 0 0 0 3 3h.5A3.5 3.5 0 0 0 10 20V4.5m4 0A3 3 0 0 1 20 6v1.5a3.5 3.5 0 0 1 1 6.5 3 3 0 0 1-3 3h-.5A3.5 3.5 0 0 1 14 20V4.5M6 10h4m4 4h4"/></>,
  sprout: <><path d="M12 22V10m0 0C8 10 5 8 5 4c4 0 7 2 7 6Zm0 5c0-4 3-6 7-6 0 4-3 6-7 6Z"/></>,
  book: <><path d="M4 5a3 3 0 0 1 3-2h5v18H7a3 3 0 0 0-3 2V5Zm16 0a3 3 0 0 0-3-2h-5v18h5a3 3 0 0 1 3 2V5Z"/></>,
  ear: <><path d="M6 8a6 6 0 0 1 12 0c0 5-5 5-5 10a3 3 0 0 1-6 0m3-7a3 3 0 1 1 4 2"/></>, lock: <><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 4v3"/></>,
  sun: <><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.93 4.93l1.42 1.42m11.3 11.3 1.42 1.42M2 12h2m16 0h2M4.93 19.07l1.42-1.42m11.3-11.3 1.42-1.42"/></>,
  pin: <><path d="M20 10c0 5-8 12-8 12S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2"/></>,
  message: <><path d="M21 15a4 4 0 0 1-4 4H8l-5 3 1.7-5A8 8 0 1 1 21 15Z"/></>, video: <><rect x="3" y="6" width="13" height="12" rx="2"/><path d="m16 10 5-3v10l-5-3"/></>,
  instagram: <><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r=".5"/></>,
  star: <><path d="m12 2 3.1 6.3 6.9 1-5 4.9 1.2 6.8-6.2-3.2L5.8 21 7 14.2l-5-4.9 6.9-1L12 2Z"/></>,
  quote: <><path d="M7 17H4a2 2 0 0 1-2-2v-2a6 6 0 0 1 6-6v3a3 3 0 0 0-3 3h2v4Zm12 0h-3a2 2 0 0 1-2-2v-2a6 6 0 0 1 6-6v3a3 3 0 0 0-3 3h2v4Z"/></>,
};
function Icon({name, size=22, fill="none"}:{name:string,size?:number,fill?:string}) { return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill={fill} stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{icons[name]}</svg> }
function Stars(){return <span className="stars" aria-label="5 estrelas">{[0,1,2,3,4].map(i=><Icon key={i} name="star" size={16} fill="currentColor"/>)}</span>}

const specialties = [
  ["brain","Ansiedade","Compreensão dos sintomas, acolhimento emocional e construção de novas formas de enfrentamento."],
  ["sprout","Compulsão alimentar","Um olhar cuidadoso para a relação com a comida, o corpo e as emoções."],
  ["heart","Conflitos com o corpo","Escuta sensível para questões de autoimagem, cobrança e sofrimento."],
  ["book","Emoções e história pessoal","Espaço para elaborar vivências, afetos e padrões que pedem cuidado."],
];
const reviews = [
  ["Matheus Silva","Ótimo atendimento. Compreensiva, atenciosa, se comunica bem e se mantém neutra. Uma excelente profissional."],
  ["Maria Eduarda Aires","Profissional incrível, dedicada e muito atenciosa, tem me ajudado muito."],
  ["Amanda Barbosa","Ótima profissional, muito atenciosa e qualificada. Indico para todos."],
  ["Thaynara Mariani","Muito bom! Profissional incrível, atendimento de qualidade, me ajudou muito."],
  ["Patricia Zaramello","Excelente profissional, prestativa e muito capacitada! Indico de olhos fechados."],
];
const office = [1,2,3,4].map(n=>`/images/consultorio-0${n}.webp`);

export default function Home() {
  const [menu,setMenu]=useState(false); const [lightbox,setLightbox]=useState<number|null>(null);
  useEffect(()=>{document.body.classList.toggle("locked",menu||lightbox!==null);},[menu,lightbox]);
  useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==="Escape"){setMenu(false);setLightbox(null)}; if(lightbox!==null&&e.key==="ArrowRight")setLightbox((lightbox+1)%4);if(lightbox!==null&&e.key==="ArrowLeft")setLightbox((lightbox+3)%4)};addEventListener("keydown",key);return()=>removeEventListener("keydown",key)},[lightbox]);
  return <>
    <header className="header"><a href="#inicio" className="brand"><img src="/images/logo-thais-borges.png" alt="Thais Borges"/></a><nav className={menu?"nav open":"nav"} aria-label="Navegação principal"><a href="#inicio" onClick={()=>setMenu(false)}>Início</a><a href="#sobre" onClick={()=>setMenu(false)}>Sobre</a><a href="#especialidades" onClick={()=>setMenu(false)}>Especialidades</a><a href="#atendimentos" onClick={()=>setMenu(false)}>Atendimentos</a><a href="#avaliacoes" onClick={()=>setMenu(false)}>Avaliações</a><a className="nav-social" href={instagram} target="_blank" rel="noreferrer"><Icon name="instagram" size={18}/> Instagram</a><a className="btn small" href={wa} target="_blank" rel="noreferrer">Agendar conversa</a></nav><button className="menu" onClick={()=>setMenu(!menu)} aria-label="Abrir menu" aria-expanded={menu}><Icon name={menu?"x":"menu"}/></button></header>
    <main>
      <section className="hero" id="inicio"><div className="hero-inner"><div className="hero-photo"><div className="orb"></div><img src="/images/thais-hero.png" alt="Psicóloga Thais Borges"/></div><div className="hero-copy"><p className="eyebrow">Thais Borges <span></span> Psicóloga Clínica <span></span> CRP 08/25356</p><h1>Psicoterapia para mulheres que desejam se escutar com mais <em>gentileza.</em></h1><p>Acompanhamento psicológico para mulheres de toda faixa etária que lidam com ansiedade, compulsão alimentar e conflitos com o próprio corpo, emoções e a própria história.</p><p>A psicoterapia é um espaço seguro, onde você não precisa dar conta de tudo sozinha, nem ser forte o tempo todo.</p><div className="actions"><a className="btn" href={wa} target="_blank" rel="noreferrer">Agendar atendimento <Icon name="arrow" size={18}/></a><a className="btn ghost" href="#atendimentos"><Icon name="video" size={18}/> Online e presencial</a></div></div></div><div className="trust"><div><strong>9</strong><span>anos de experiência</span></div><div><strong>5,0</strong><span><Stars/> 94 avaliações</span></div><div><Icon name="pin"/><span>Londrina e online</span></div></div></section>
      <section className="section" id="sobre"><div className="about"><img src="/images/thais-sobre.png" alt="Thais Borges em um ambiente acolhedor"/><div><p className="eyebrow">Sobre o processo</p><h2>Um espaço de escuta, cuidado e compreensão.</h2><p>Acredito que os sintomas não surgem por acaso. Eles são formas de comunicação — sinais de algo interno que pede escuta, cuidado e compreensão, não julgamento.</p><p>Aqui, é possível se escutar com mais gentileza, se reorganizar internamente e construir novos sentidos para aquilo que você viveu — e para quem você está se tornando.</p><p className="signature">Se você sente que algo dentro de você pede atenção, talvez esse seja um bom começo.</p></div></div></section>
      <section className="section soft" id="especialidades"><div className="section-head"><p className="eyebrow">Cuidado direcionado</p><h2>Especialidades</h2><p>Um acompanhamento atento à singularidade da sua história e ao que você vive hoje.</p></div><div className="cards">{specialties.map(([icon,title,text])=><article className="card" key={title}><span className="icon-box"><Icon name={icon}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className="section process"><div className="section-head"><p className="eyebrow">Seu tempo, seu caminho</p><h2>Como funciona a psicoterapia</h2></div><div className="steps">{[["ear","Escuta sem julgamento","Um espaço de acolhimento verdadeiro para você ser quem é."],["lock","Espaço seguro","Confidencial, ético e pensado para o seu bem-estar."],["sprout","Reorganização interna","Mais clareza, equilíbrio e conexão consigo mesma."],["sun","Novos sentidos para sua história","Transforme vivências em aprendizados e caminhos possíveis."]].map(([i,t,p],n)=><article key={t}><span className="step-number">0{n+1}</span><span className="round-icon"><Icon name={i}/></span><h3>{t}</h3><p>{p}</p></article>)}</div></section>
      <section className="section office" id="atendimentos"><div className="office-info"><p className="eyebrow">Atendimento</p><h2>Presencial em Londrina e online</h2><p className="lead">Ambiente acolhedor, pensado para o seu cuidado.</p><ul><li><Icon name="pin"/><span>R. Gomes Carneiro, 163<br/>Boa Vista, Londrina - PR</span></li><li><Icon name="message"/><span>WhatsApp: +55 43 9674-0022</span></li><li><Icon name="video"/><span>Atendimentos presenciais e online</span></li></ul><div className="actions"><a className="btn" href={wa} target="_blank" rel="noreferrer">Agendar atendimento</a><a className="btn ghost" href={instagram} target="_blank" rel="noreferrer"><Icon name="instagram" size={18}/> Ver Instagram</a></div></div><div className="gallery">{office.map((src,i)=><button key={src} className={i===0?"large":""} onClick={()=>setLightbox(i)} aria-label={`Ampliar foto ${i+1} do consultório`}><img src={src} alt={`Consultório Thais Borges, foto ${i+1}`}/><span>Ver foto</span></button>)}</div></section>
      <section className="section reviews" id="avaliacoes"><div className="section-head"><p className="eyebrow">Experiências reais</p><h2>Avaliações de quem já passou por aqui</h2><div className="rating"><b>5,0</b><Stars/><span>94 avaliações no Google</span></div></div><div className="review-track">{reviews.map(([name,text])=><article className="review" key={name}><Icon name="quote" size={28}/><Stars/><p>“{text}”</p><strong>{name}</strong><span>Paciente verificado</span></article>)}</div></section>
      <section className="final-cta"><div><p className="eyebrow">Comece por você</p><h2>Você não precisa enfrentar tudo sozinha.</h2><p>Se sente que algo dentro de você pede atenção, entre em contato e dê o primeiro passo.</p><div className="actions"><a className="btn light" href={wa} target="_blank" rel="noreferrer"><Icon name="message" size={18}/> Falar no WhatsApp</a><a className="btn outline" href={instagram} target="_blank" rel="noreferrer"><Icon name="instagram" size={18}/> Acompanhar no Instagram</a></div></div><img src="/images/monograma-tb.png" alt="Monograma TB"/></section>
    </main>
    <footer><div className="footer-top"><div className="footer-brand"><img src="/images/monograma-tb.png" alt=""/><p>Thais Borges <span>Psicóloga Clínica • CRP 08/25356</span></p></div><div><h3>Atendimentos</h3><p>Presenciais em Londrina e online.</p><p>R. Gomes Carneiro, 163 - Boa Vista</p></div><div><h3>Contato</h3><a href={wa} target="_blank" rel="noreferrer">+55 43 9674-0022</a><a href={instagram} target="_blank" rel="noreferrer">Instagram</a></div><a className="top" href="#inicio">Voltar ao topo ↑</a></div><div className="footer-bottom"><span>© 2026 Thais Borges. Todos os direitos reservados.</span><span>Desenvolvido por <b>GM Web Studio</b></span></div></footer>
    <div className="floating"><a href={instagram} target="_blank" rel="noreferrer" aria-label="Instagram"><Icon name="instagram"/></a><a className="whats" href={wa} target="_blank" rel="noreferrer" aria-label="WhatsApp"><Icon name="message"/></a></div>
    {lightbox!==null&&<div className="lightbox" role="dialog" aria-modal="true" aria-label="Galeria do consultório" onClick={()=>setLightbox(null)}><button className="close" onClick={()=>setLightbox(null)} aria-label="Fechar"><Icon name="x"/></button><button className="prev" onClick={e=>{e.stopPropagation();setLightbox((lightbox+3)%4)}} aria-label="Foto anterior">‹</button><img onClick={e=>e.stopPropagation()} src={office[lightbox]} alt={`Consultório, foto ampliada ${lightbox+1}`}/><button className="next" onClick={e=>{e.stopPropagation();setLightbox((lightbox+1)%4)}} aria-label="Próxima foto">›</button><span>{lightbox+1} / 4</span></div>}
  </>
}
